resources:
  repositories:
  - repository: MobileCelestia
    type: github
    endpoint: GithubAuth
    name: celestiamobile/MobileCelestia

trigger: none

pool:
  vmImage: macos-15

steps:
- checkout: MobileCelestia
  fetchDepth: 0
- checkout: self

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '9f9dcde1-dcba-4537-8214-71c8a03b99a0'
    pipeline: '10'
    buildVersionToDownload: 'specific'
    buildId: '$(BUILD_ID)'
    downloadType: 'single'
    artifactName: 'iphoneos-appStore-openGL-product'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: 'Download Build'

- task: DownloadSecureFile@1
  name: appStoreConnectKey
  displayName: 'Download JSON Key'
  inputs:
    secureFile: 'appstore-connect-key.json'

- script: |
    cd MobileCelestia
    git checkout $(BRANCH)
    cd fastlane/ios
    CHANGELOG=$(cat $(System.DefaultWorkingDirectory)/upload-release/release-notes-apple.txt)
    FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=$CI_FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD fastlane pilot upload --ipa $(System.ArtifactsDirectory)/iphoneos-appStore-openGL-product/Celestia.ipa --submit_beta_review --api_key_path $(appStoreConnectKey.secureFilePath) --changelog "$CHANGELOG"
  env:
    CI_FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: $(FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD)
  displayName: 'Upload'