trigger: none

pool:
  vmImage: ubuntu-24.04

steps:

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '9f9dcde1-dcba-4537-8214-71c8a03b99a0'
    pipeline: '8'
    buildVersionToDownload: 'specific'
    buildId: '$(BUILD_ID)'
    downloadType: 'single'
    artifactName: 'CelestiaSL-x64'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: 'Download Sideload Build (x64)'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '9f9dcde1-dcba-4537-8214-71c8a03b99a0'
    pipeline: '8'
    buildVersionToDownload: 'specific'
    buildId: '$(BUILD_ID)'
    downloadType: 'single'
    artifactName: 'CelestiaSL-arm64'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: 'Download Sideload Build (arm64)'

- script: |
    VERSION=$(ls -d $(System.ArtifactsDirectory)/CelestiaSL-arm64/CelestiaWinUI_*_*_Test | head -1 | sed 's/.*CelestiaWinUI_\(.*\)_.*_Test/\1/')
    echo "##vso[task.setvariable variable=Version]$VERSION"
  displayName: 'Set Version Variable'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.ArtifactsDirectory)/CelestiaSL-x64'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/CelestiaWinUI_$(Version)_x64.zip'
    replaceExistingArchive: true
  displayName: 'Create Archive (x64)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.ArtifactsDirectory)/CelestiaSL-arm64'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/CelestiaWinUI_$(Version)_arm64.zip'
    replaceExistingArchive: true
  displayName: 'Create Archive (arm64)'

- script: |
    CELESTIA_REPO_COMMIT=$(git ls-remote https://github.com/celestiamobile/Celestia $(BRANCH) | cut -f 1)
    CELESTIA_LOCALIZATION_REPO_COMMIT=$(git ls-remote https://github.com/celestiamobile/CelestiaLocalization $(BRANCH) | cut -f 1)
    CELESTIA_CONTENT_REPO_COMMIT=$(curl -s "https://raw.githubusercontent.com/celestiamobile/CelestiaUWP/$(BRANCH)/jobs/build.yml" | awk -F"'" '/contentCommitHash/ {print $2}')
    echo https://github.com/celestiamobile/Celestia/commit/$CELESTIA_REPO_COMMIT >> release-notes-uwp.txt
    echo https://github.com/celestiamobile/CelestiaLocalization/commit/$CELESTIA_LOCALIZATION_REPO_COMMIT >> release-notes-uwp.txt
    echo https://github.com/CelestiaProject/CelestiaContent/commit/$CELESTIA_CONTENT_REPO_COMMIT >> release-notes-uwp.txt
  displayName: 'Update Release Notes'

- script: |
    CELESTIA_UWP_REPO_COMMIT=$(git ls-remote https://github.com/celestiamobile/CelestiaUWP $(BRANCH) | cut -f 1)
    echo "##vso[task.setvariable variable=CommitHash]$CELESTIA_UWP_REPO_COMMIT"
  displayName: 'Set Commit Hash Variable'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'GithubAuth'
    repositoryName: 'celestiamobile/CelestiaUWP'
    action: 'create'
    target: $(CommitHash)
    tagSource: 'userSpecifiedTag'
    tag: '$(Version)'
    title: '$(Version)'
    releaseNotesFilePath: '$(System.DefaultWorkingDirectory)/release-notes-uwp.txt'
    isDraft: true
    addChangeLog: false
    assets: '$(System.DefaultWorkingDirectory)/CelestiaWinUI_$(Version)_*.zip'
  displayName: 'Release'
