trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '9f9dcde1-dcba-4537-8214-71c8a03b99a0'
    pipeline: '10'
    buildVersionToDownload: 'specific'
    buildId: '$(BUILD_ID)'
    downloadType: 'single'
    artifactName: 'macosx-developerID-openGL-product'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: 'Download macOS Sideload Build'

- script: |
    tree $(System.ArtifactsDirectory)