resources:
  repositories:
  - repository: CelestiaUWP
    type: github
    endpoint: GithubAuth
    name: celestiamobile/CelestiaUWP

trigger: none

pool:
  vmImage: 'windows-2022'

steps:
- checkout: CelestiaUWP
  fetchDepth: 0
- checkout: self

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '9f9dcde1-dcba-4537-8214-71c8a03b99a0'
    pipeline: '8'
    buildVersionToDownload: 'specific'
    buildId: '$(BUILD_ID)'
    downloadType: 'single'
    artifactName: 'msixupload'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: 'Download Build'

- bash: |
    VERSION=$(curl -s "https://raw.githubusercontent.com/celestiamobile/CelestiaUWP/$(BRANCH)/CelestiaWinUI/Package.appxmanifest" | awk -F'"' '/Version=/ {print $2; exit}')
    echo "##vso[task.setvariable variable=Version]$VERSION"
    cd CelestiaUWP
    git checkout $(BRANCH)
  displayName: 'Set Version Variable'

- pwsh: |
    Install-Module -Name StoreBroker -Force
  displayName: Setup Microsoft Store CLI

- pwsh: |
    # Login
    $user = $Env:PARTNER_CENTER_CLIENT_ID
    $password = ConvertTo-SecureString $Env:PARTNER_CENTER_CLIENT_SECRET -AsPlainText -Force
    $Cred = New-Object System.Management.Automation.PSCredential($user, $password)
    Set-StoreBrokerAuthentication -TenantId $Env:PARTNER_CENTER_TENANT_ID -Credential $Cred
    $appId = $Env:PARTNER_CENTER_APP_ID

    # Read release notes
    $releaseNotes = Get-Content upload-release\release-notes-uwp.txt -Raw

    $folders = Get-ChildItem -Recurse -Directory -Path CelestiaUWP\CelestiaUWP\metadata
    foreach ($folder in $folders) {
      # Replace RELEASE_NOTES_PLACEHOLDER in PDP.xml with release notes
      $pdpPath = Join-Path $folder.FullName "PDP.xml"
      (Get-Content $pdpPath) -replace "RELEASE_NOTES_PLACEHOLDER", $releaseNotes | Set-Content $pdpPath
      (Get-Content $pdpPath) -replace "RELEASE_VERSION_PLACEHOLDER", "$(Version)" | Set-Content $pdpPath

      if ($folder.Name -eq "en") {
        continue
      }
      
      # Copy screenshot files from en
      Copy-Item -Path "CelestiaUWP\CelestiaUWP\metadata\en\Output*.png" -Destination $folder.FullName -Force
    }

    # Create directory for update
    mkdir -Path update
    Move-Item -Path "CelestiaUWP\CelestiaUWP\metadata" -Destination update\$(Version) -Force

    # Create submission package
    New-SubmissionPackage -ConfigPath update\$(Version)\submission.json -AppxPath "$(System.ArtifactsDirectory)\msixupload\CelestiaWinUI_$(Version)_x64_bundle.msixupload" -PDPRootPath update -ImagesRootPath update -Release $(Version) -OutPath out -OutName package

    # Create new submission
    $sub = New-ApplicationSubmission -AppId $appId -Force
    # Parse submission meta
    $json = (Get-Content out\package.json -Encoding UTF8) | ConvertFrom-Json
    # Delete old packages
    foreach ($package in $sub.applicationPackages) {
      if ($package.id -ne "2000000000083240524") {
        $package.fileStatus = "PendingDelete"
      }
    }
    # add new packages
    $sub.applicationPackages += $json.applicationPackages
    # Upload submission meta
    Set-ApplicationSubmission -AppId $appId -UpdatedSubmission $sub
    # Upload submission package
    Set-SubmissionPackage -PackagePath out\package.zip -UploadUrl ($sub.fileUploadUrl)
    # Commit changes
    Complete-ApplicationSubmission -AppId $appId -SubmissionId ($sub.id)
  env:
    PARTNER_CENTER_CLIENT_ID: $(PARTNER_CENTER_CLIENT_ID)
    PARTNER_CENTER_CLIENT_SECRET: $(PARTNER_CENTER_CLIENT_SECRET)
    PARTNER_CENTER_TENANT_ID: $(PARTNER_CENTER_TENANT_ID)
    PARTNER_CENTER_APP_ID: $(PARTNER_CENTER_APP_ID)
  displayName: Upload Release
